segundo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'segundo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^preguntas/$', 'preguntasyrespuestas.views.index', name="preguntas"),
    url(r'^$', 'segundo.views.homepage', name="homepage"),
    url(r'^login/$', 'segundo.views.login_page', name="login"),
    url(r'^logout/$', 'segundo.views.logout_view', name="logout"),
    url(r'^preguntas/crear/$', 'preguntasyrespuestas.views.pregunta_crear', name="pregunta_crear"),
    url(r'^preguntas/editar/(?P<pregunta_id>\d+)/$', 'preguntasyrespuestas.views.pregunta_editar', name='pregunta_editar'),
    url(r'^preguntas/(?P<pregunta_id>\d+)/$', 'preguntasyrespuestas.views.pregunta_detalle', name='pregunta_detalle'),


    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

app/models.py
from django.db import models

# Create your models here.

preguntasyrespuestas/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Pregunta(models.Model):
	asunto = models.CharField(max_length=200)
	descripcion = models.TextField()
	fecha_publicacion = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.asunto

	def publicado_hoy(self):
		return self.fecha_publicacion.date() == timezone.now().date()

	publicado_hoy.boolean = True
	publicado_hoy.descripcion_corta = "Preguntado hoy"


class Respuesta(models.Model):
	pregunta = models.ForeignKey(Pregunta)
	contenido = models.TextField()
	mejor_respuesta = models.BooleanField("Respuesta preferida",
	 										default=False)

	def __str__(self):
		return self.contenido

segundo/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput())

app/views.py
from django.shortcuts import render

# Create your views here.

preguntasyrespuestas/views.py
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from preguntasyrespuestas.models import Pregunta
from django.template import RequestContext
from preguntasyrespuestas.form import PreguntaForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
	preguntas = Pregunta.objects.all()
	return render_to_response('preguntasyrespuestas/index.html', 
							 {'preguntas': preguntas},
							 context_instance=RequestContext(request))

def pregunta_detalle(request, pregunta_id):
	pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
	return render_to_response('preguntasyrespuestas/pregunta_detalle.html',
							 {'pregunta': pregunta},
							 context_instance=RequestContext(request))

@login_required
def pregunta_crear(request):
	if request.method == 'POST':
		form = PreguntaForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('preguntas')
	else:
		form = PreguntaForm()
	return render_to_response('preguntasyrespuestas/pregunta_crear.html',
							 {'form': form},
	 						 context_instance=RequestContext(request))

@login_required
def pregunta_editar(request, pregunta_id):
	pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
	if request.method == 'POST':
		form = PreguntaForm(request.POST, instance=pregunta)
		if form.is_valid():
			form.save()
			return redirect('pregunta_detalle', pregunta_id)
	else:
		form = PreguntaForm(instance=pregunta)
	return render_to_response('preguntasyrespuestas/pregunta_editar.html',
							 {'form': form},
	 						 context_instance=RequestContext(request))
#[template_directory]/preguntasyrespuestas/index.html

segundo/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from segundo.forms import LoginForm
from django.contrib.auth import authenticate, login, logout

def login_page(request):
	message = None
	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					message = "Te has identificado en modo correcto"
				else:
					message = "Tu usuario esta inactivo"
			else:
				message = "Nombre de usuario y/o password incorrectos!"
	else:
		form = LoginForm()
	return render_to_response('login.html',
							 {'message': message, 'form': form},
							  context_instance=RequestContext(request))			

def homepage(request):
	return render_to_response('homepage.html', context_instance=RequestContext(request))

def logout_view(request):
		logout(request)
		return redirect('homepage')	

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Curso de django. | {% block title %}Inicio{% endblock %}</title>
</head>
<body>
	<div class="header">
		{% if user.is_authenticated %}
			<p>Bienvenido, <b>{{ user.username }}</b> | <a href="{% url "logout" %}">Log out</a></p>
		{% else %}
			<p>Bienvenido, Por favor <a href="{% url "login" %}">Log in</a></p>
		{% endif %}
		<h1>Curso de Django. Videotutoriales.com</h1>
	</div>
	<div class="content">
		{% block content %}{% endblock %}
	</div>
	<div class="navigation">
		<p><a href="{% url "homepage" %}">Inicio</a> | <a href="{% url "preguntas" %}">Preguntas</a></p>
	</div>
</body>
</html>

templates/form_snippets.html
{% for field in form %}
	<div class="field_container">
		{{ field.errors }}
		{{ field.label_tag }} </br>
		{{ field }}
	</div>
{% endfor %}

templates/homepage.html
{% extends "base.html" %}
{% block title %} Bienvenido {% endblock %}
{% block content %}
	<h3>Bienvenido, esta es nuestra pagina de inicio</h3>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
	<h1>Login</h1>
	{% if message %}
		<b>{{message}}</b>
	{% endif %}
	<form action="" method="post">{% csrf_token %} 
		{{form.as_p}}
		<input type="submit" value="LogIn">
	</form>
{% endblock %}

templates/preguntasyrespuestas/index.html
{% extends "base.html" %}
{% block title %} Preguntas {% endblock %}
{% block content %}
	<p><a href="{% url "pregunta_crear" %}">Crear una pregunta</a></p>
	{% for pregunta in preguntas %}
		<a href="{% url "pregunta_detalle" pregunta.id %}">¿ {{ pregunta.asunto }} ?</a><br/>
	{% endfor %}
{% endblock %}

templates/preguntasyrespuestas/pregunta_crear.html
{% extends "base.html" %}
{% block title %} Crear una pregunta {% endblock %}
{% block content %}
	<form action="" method="post">{% csrf_token %}
		{% include "preguntasyrespuestas/form_snippets.html" %}
		<input type="submit" value="Enviar">
	</form>
{% endblock %}

templates/preguntasyrespuestas/pregunta_detalle.html
{% extends "base.html" %}
{% block title %} Detalle de pregunta {% endblock %}
{% block content %}
	<h2>¿ {{ pregunta.asunto }} ?</h2>
	<p><a href="{% url "pregunta_editar" pregunta.id %}">Editar esta pregunta</a></p>
		<p><b>Publicado:</b> {{ pregunta.fecha_publicacion|date:"D, d/m/y" }}</p>
		<p>
			{% if pregunta.descripcion %}
				{{pregunta.descripcion}}
			{% else %}
				No se ha incluido la descripcion
			{% endif %}
		</p>
		<h3>Respuestas</h3>
		<ul>
			{% for respuesta in pregunta.respuesta_set.all %}
				<li>{{respuesta.contenido|safe}}</li>
			{% empty %}
				<li>Aún no hay respuestas</li>
			{% endfor %}
		</ul>
{% endblock %}

templates/preguntasyrespuestas/pregunta_editar.html
{% extends "base.html" %}
{% block title %} Editar una pregunta {% endblock %}
{% block content %}
	<form action="" method="post">{% csrf_token %}
		{% include "preguntasyrespuestas/form_snippets.html" %}
		<input type="submit" value="Enviar">
	</form>
{% endblock %}